name: Purge image cache

on:
  schedule:
    - cron: '54 18 * * *'

jobs:
  purge:
    runs-on: ubuntu-18.04
    steps:

    - run: >
        curl -sL https://github.com/${GITHUB_REPOSITORY} |
        grep -oE '<img src="https?://camo.githubusercontent.com/[^"]+' |
        sed -e 's/<img src="//' |
        xargs -I % curl -sX PURGE %
